apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: snake-app
  labels:
    app: game
    application: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: snake-game
        image: balakrishna625/snake:latest
