apiVersion: v1
kind: Pod
metadata:
  name: ebs-test-pod
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a 
  containers:
  - name: app
    image: public.ecr.aws/docker/library/busybox:stable
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: ebs-gp3-test
