apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv-12345
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-005683812fa642794
    fsType: ext4
