apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-frontend
  labels:
    app: weather-dashboard
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-dashboard
      component: frontend
  template:
    metadata:
      labels:
        app: weather-dashboard
        component: frontend
    spec:
      containers:
      - name: weather-ui
        image: balakrishna625/weather-frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: weather-frontend-service
  labels:
    app: weather-dashboard
    component: frontend
spec:
  selector:
    app: weather-dashboard
    component: frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: LoadBalancer